services:
  kc:
    image: quay.io/keycloak/keycloak:23.0.3
    container_name: kc
    restart: always
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://____<IP>____:5432/kc_db
      - KC_DB_USERNAME=kc_user
      - KC_DB_PASSWORD=P@ssw0rdSkills
      - KC_BOOTSTRAP_ADMIN_USERNAME='admin'
      - KC_BOOTSTRAP_ADMIN_PASSWORD='P@ssw0rd'
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=P@ssw0rd
      - KC_HOSTNAME=____<IP>____
    command: start-dev
    network_mode: host
