version: '3.7'

services:
  # PostgreSQL
  pgsql:
    build: ./pgsql
    image: pgsql:as25
    container_name: pgsql-server
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: P@ssw0rdSkills
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - zabbix-net
    restart: always

  # Zabbix Server
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-6.4-latest
    container_name: zabbix-server
    depends_on:
      - pgsql
    environment:
      DB_SERVER_HOST: pgsql
      POSTGRES_USER: zabbix_user
      POSTGRES_PASSWORD: P@ssw0rdSkills
      POSTGRES_DB: zabbix_db
    ports:
      - "10051:10051"
    networks:
      - zabbix-net
    restart: unless-stopped

  # Zabbix Web
  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-6.4-latest
    container_name: zabbix-web
    depends_on:
      - pgsql
      - zabbix-server
    environment:
      DB_SERVER_HOST: pgsql
      POSTGRES_USER: zabbix_user
      POSTGRES_PASSWORD: P@ssw0rdSkills
      POSTGRES_DB: zabbix_db
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: Europe/Moscow
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl
    networks:
      - zabbix-net
    restart: unless-stopped

networks:
  zabbix-net:
    driver: bridge

volumes:
  pgdata:
