version: '3.7'

services:
  # Zabbix Server
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-6.4-latest
    container_name: zabbix-server
    environment:
      DB_SERVER_HOST: cloud-infra.atom25.local
      POSTGRES_USER: zabbix_user
      POSTGRES_PASSWORD: P@ssw0rdSkills
      POSTGRES_DB: zabbix_db
    ports:
      - "10051:10051"
    networks:
      - zabbix-net
    restart: unless-stopped

  # Zabbix Web
  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-6.4-latest
    container_name: zabbix-web
    depends_on:
      - zabbix-server
    environment:
      DB_SERVER_HOST: cloud-infra.atom25.local
      POSTGRES_USER: zabbix_user
      POSTGRES_PASSWORD: P@ssw0rdSkills
      POSTGRES_DB: zabbix_db
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: Europe/Moscow
    ports:
      - "80:8080"
    networks:
      - zabbix-net
    restart: unless-stopped

networks:
  zabbix-net:
    driver: bridge