services:
  proxy:
    image: nginx:alpine
    container_name: proxy
    volumes:
      - ./certs/:/etc/ssl/
      - ./proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
